name: Notes App Pipeline

# Set up how the workflow is triggered
on:

  # Trigger the workflow on push or pull request events on the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow triggering this workflow manually from the Actions tab
  workflow_dispatch:

# Set up the job for this workflow
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [pgadmin, postgres, mysql]
        python-version: [3.9]
        include:
          - db: postgres
            db_port: 5432
          - db: mysql
            db_port: 5433
    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin12390
          POSTGRES_DB: notes_project_db
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
      pgadmin:
        image: dpage/pgadmin4:5.2
        env:
          PGADMIN_DEFAULT_PASSWORD: admin12390
          PGADMIN_LISTEN_PORT: 5433
        ports:
          - 5433:5433
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install braintree mysqlclient apprise pytest

    - name: Run migrations
      run: python manage.py migrate
     
    - name: Run all tests
      env:
        DJANGO_SETTINGS_MODULE: notes_project.settings
      run: |
        python manage.py test
